### PR TITLE
feature: enable live disk snapshot

### PR DESCRIPTION
**Pull request by baby-gnu**
The `snap_create_live` is just a copy of `snap_create` with the added
logic to freeze or suspend the VM.

### CODE REVIEW

**Comment by baby-gnu** [comment]
This should fix #7.

**Comment by cloudweavers** [comment]
Dear Daniel, thanks for your contribution. The reason why it was incomplete is... that we don't use snapshots (not in the same way, at least) in our version of the embedded OpenNebula. I have accepted your pull, thanks for helping!

**Comment by baby-gnu** [comment]
Thanks a lot @cloudweavers 

it's a no-op unless you configure `/etc/one/vmm_exec/vmm_execrc`.

Regards.

**Comment by baby-gnu** [comment]
By the way, we use a hook to create a first initial snapshot of each VM disk at startup

- we mostly use OpenNebula as a development platform
- users do not have access to `delete-recreate` anymore (it became a `onevm recover` option quite a long time ago)
- use use a lot a `deploy` → `hack` → `build a deb package` → `reset` → `upgrade` → `test` workflow, the reset is easy with the initial snapshot ;-)

Regards.

**Pull request merged**
